/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************/


#include	"STD_TYPES.h"
#include	"BIT_MATH.h"
#include 	"SevenSeg.h"
#include	"RCC_interface.h"
#include	"GPIO_interface.h"
#include 	"LED.h"

int main(void)
{

	/*Enable System Clock*/
	RCC_voidSysClkInt();

	/* Enable RCC for ADC and GPIOA*/
	RCC_voidEnablePerClk(RCC_APB2,GPIOA_RCC);
	RCC_voidEnablePerClk(RCC_APB2,GPIOB_RCC);
	RCC_voidEnablePerClk(RCC_APB2,GPIOC_RCC);
	SevenSeg_init();

	GPIO_voidSetPinMode(GPIOA, PIN0, GPIO_INPUT_PULL_UP_DOWN);
	GPIO_voidSetPinMode(GPIOA, PIN1, GPIO_INPUT_PULL_UP_DOWN);
	GPIO_voidSetPinValue(GPIOA, PIN0, GPIO_HIGH);
	GPIO_voidSetPinValue(GPIOA, PIN1, GPIO_HIGH);


	led_init(GPIOA, PIN2);
	led_init(GPIOC, PIN13);

	while(1)
	{
		if	((!GPIO_u8GetPinValue(GPIOA, PIN1))&&(!GPIO_u8GetPinValue(GPIOA, PIN0)))
		{

			GPIO_voidSetPinValue(GPIOA, PIN2, GPIO_HIGH);
			Sevenseg_write(1);
		}

		else if(!GPIO_u8GetPinValue(GPIOA, PIN0))
		{
			GPIO_voidSetPinValue(GPIOC, PIN13, GPIO_HIGH);
			Sevenseg_write(0);
		}

		else
		{
			GPIO_voidSetPinValue(GPIOC, PIN13, GPIO_LOW);
			GPIO_voidSetPinValue(GPIOA, PIN2, GPIO_LOW);
		}




	}
}
